Module 4
polylearner/DevOps-Course-Starter pull request #4
Opened 2020-11-30 15:43 UTC by polylearner

Vagrant file work for Module 4 Project exercise.

2020-12-17 11:04 UTC, Jonesey13 requested changes
This is nearly there but needs a couple of additions/changes:

- Please document how to run the VM in your `README.md` file
- Please add a trigger stage to your vagrantfile
- The script breaks trying to run pyenv atm (although it skips past it and uses the prepackaged python 3.6 instead thanks to use of `venv`).

2020-12-17 11:04 UTC, Jonesey13 commented on Vagrantfile
> +                source ~/.profile
But we've written our commands to `~/.bash_profile`?

2020-12-17 11:04 UTC, Jonesey13 commented on Vagrantfile
> +                python3 -m venv ~/venv
Why do we need these lines when python3 comes with `venv` anyway?

2020-12-17 11:04 UTC, Jonesey13 commented on Vagrantfile
> +            source ~/venv/bin/activate
Again we're using python before we're installed python!

2020-12-17 11:04 UTC, Jonesey13 commented on Vagrantfile
> +            pip install --upgrade pip
Our package manager is poetry and not pip

2021-02-11 13:58 UTC, JackMead approved these changes
Thanks for making those changes, I'm happy for you to merge this now as is.

2021-02-11 14:06 UTC, merged